<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="1" total="1" passed="0">
  <reporter-output>
  </reporter-output>
  <suite name="Default suite" duration-ms="32300" started-at="2017-05-10T08:38:29Z" finished-at="2017-05-10T08:39:01Z">
    <groups>
    </groups>
    <test name="Default test" duration-ms="32300" started-at="2017-05-10T08:38:29Z" finished-at="2017-05-10T08:39:01Z">
      <class name="bahaso.testing.android.LostWordType_test">
        <test-method status="PASS" signature="beforeclass()[pri:0, instance:bahaso.testing.android.LostWordType_test@13805618]" name="beforeclass" is-config="true" duration-ms="8" started-at="2017-05-10T15:38:29Z" finished-at="2017-05-10T15:38:29Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- beforeclass -->
        <test-method status="PASS" signature="beforeMethod()[pri:0, instance:bahaso.testing.android.LostWordType_test@13805618]" name="beforeMethod" is-config="true" duration-ms="27738" started-at="2017-05-10T15:38:29Z" finished-at="2017-05-10T15:38:57Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- beforeMethod -->
        <test-method status="FAIL" signature="test1()[pri:0, instance:bahaso.testing.android.LostWordType_test@13805618]" name="test1" duration-ms="4533" started-at="2017-05-10T15:38:57Z" finished-at="2017-05-10T15:39:01Z">
          <exception class="java.lang.ArrayIndexOutOfBoundsException">
            <message>
              <![CDATA[-1]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.ArrayIndexOutOfBoundsException: -1
	at java.util.ArrayList.elementData(Unknown Source)
	at java.util.ArrayList.get(Unknown Source)
	at bahaso.testing.androidElement.ExercisePage.scrollTo(ExercisePage.java:29)
	at bahaso.testing.androidElement.LostWordType.answerRight(LostWordType.java:41)
	at bahaso.testing.android.LostWordType_test.test1(LostWordType_test.java:55)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:100)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:646)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:811)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1137)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:753)
	at org.testng.TestRunner.run(TestRunner.java:607)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:368)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:363)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:321)
	at org.testng.SuiteRunner.run(SuiteRunner.java:270)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1284)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1209)
	at org.testng.TestNG.runSuites(TestNG.java:1124)
	at org.testng.TestNG.run(TestNG.java:1096)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:132)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:236)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:81)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.ArrayIndexOutOfBoundsException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- test1 -->
      </class> <!-- bahaso.testing.android.LostWordType_test -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
